# Generated by Django 2.0.3 on 2018-04-12 03:46

from django.db import migrations, models
import django.db.models.deletion
import gm2m.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(blank=True, max_length=80)),
                ('duration', models.IntegerField(default=0)),
                ('description', models.CharField(default='default', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AlarmEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_type', models.CharField(choices=[('US', 'User'), ('DV', 'Device'), ('ND', 'No-Device')], default='US', max_length=2)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('finished', models.DateTimeField(null=True)),
                ('description', models.CharField(default='description', max_length=255, null=True)),
                ('alarm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='example.Alarm')),
                ('content_type', gm2m.fields.GM2MField(through_fields=('gm2m_src', 'gm2m_tgt', 'gm2m_ct', 'gm2m_pk'))),
            ],
        ),
    ]
